-- CULT Dashboard — Supabase Schema
-- Run this in the Supabase SQL editor to bootstrap all tables.

-- Enable pgvector extension (for Phase 3 RAG)
create extension if not exists vector;

-- ──────────────────────────────────────────────────────────────
-- Profiles table (extends Supabase auth.users)
-- ──────────────────────────────────────────────────────────────
create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  role text not null default 'client' check (role in ('admin', 'client')),
  name text not null default '',
  email text not null default '',
  is_active boolean not null default true,
  ig_username text,
  ig_user_id text,
  ig_access_token text,
  yt_channel_id text,
  tiktok_handle text,
  onboarding_completed boolean not null default false,
  content_insights_json jsonb,
  content_insights_updated_at timestamptz,
  created_at timestamptz not null default now()
);

-- Auto-create profile on signup
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, email, name)
  values (new.id, new.email, coalesce(new.raw_user_meta_data->>'name', ''));
  return new;
end;
$$ language plpgsql security definer;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- ──────────────────────────────────────────────────────────────
-- Onboarding
-- ──────────────────────────────────────────────────────────────
create table public.onboarding (
  id uuid primary key default gen_random_uuid(),
  profile_id uuid not null references public.profiles(id) on delete cascade unique,
  niche text default '',
  target_audience text default '',
  current_followers integer default 0,
  monthly_revenue text default '',
  main_goal text default '',
  biggest_challenge text default '',
  content_experience text default '',
  posting_frequency text default '',
  brand_voice text default '',
  unique_story text default '',
  competitors_they_admire text default '',
  what_tried_before text default '',
  why_joined_cult text default '',
  raw_data jsonb default '{}',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- ──────────────────────────────────────────────────────────────
-- Client reels (scraped weekly)
-- ──────────────────────────────────────────────────────────────
create table public.client_reels (
  id uuid primary key default gen_random_uuid(),
  profile_id uuid not null references public.profiles(id) on delete cascade,
  reel_id text not null,
  date text,
  scraped_week text,
  views integer default 0,
  likes integer default 0,
  comments integer default 0,
  saves integer default 0,
  shares integer default 0,
  duration_sec real,
  transcript text default '',
  format_type text default '',
  hook text default '',
  caption text default '',
  hashtags text[] default '{}',
  content_pillar text default '',
  created_at timestamptz not null default now(),
  unique(profile_id, reel_id)
);

-- ──────────────────────────────────────────────────────────────
-- Competitor reels (global — scraped from public accounts)
-- ──────────────────────────────────────────────────────────────
create table public.competitor_reels (
  id uuid primary key default gen_random_uuid(),
  account text not null,
  reel_id text not null unique,
  scraped_week text,
  date text,
  views integer default 0,
  likes integer default 0,
  comments integer default 0,
  transcript text default '',
  format_type text default '',
  hook text default '',
  caption text default '',
  hashtags text[] default '{}',
  created_at timestamptz not null default now()
);

-- ──────────────────────────────────────────────────────────────
-- Weekly scripts (per client, generated by the weekly runner)
-- ──────────────────────────────────────────────────────────────
create table public.weekly_scripts (
  id uuid primary key default gen_random_uuid(),
  profile_id uuid references public.profiles(id) on delete cascade,
  week_start date not null,
  scripts_md text not null default '',
  script_count integer default 7,
  created_at timestamptz not null default now(),
  unique(profile_id, week_start)
);

-- ──────────────────────────────────────────────────────────────
-- Weekly competitor intelligence reports (global)
-- ──────────────────────────────────────────────────────────────
create table public.weekly_reports (
  id uuid primary key default gen_random_uuid(),
  week_start date not null unique,
  report_md text not null default '',
  trending_topics jsonb default '[]',
  top_hooks jsonb default '[]',
  created_at timestamptz not null default now()
);

-- ──────────────────────────────────────────────────────────────
-- Content pillars (computed weekly per client)
-- ──────────────────────────────────────────────────────────────
create table public.content_pillars (
  id uuid primary key default gen_random_uuid(),
  profile_id uuid not null references public.profiles(id) on delete cascade,
  week text not null,
  pillar_name text not null,
  reel_count integer default 0,
  avg_views real default 0,
  avg_likes real default 0,
  sample_hooks text[] default '{}',
  created_at timestamptz not null default now(),
  unique(profile_id, week, pillar_name)
);

-- ──────────────────────────────────────────────────────────────
-- Knowledge chunks for pgvector RAG (Phase 3)
-- ──────────────────────────────────────────────────────────────
create table public.knowledge_chunks (
  id uuid primary key default gen_random_uuid(),
  content text not null,
  embedding vector(1536),
  source_type text not null check (source_type in (
    'will_script', 'client_reel', 'competitor_reel',
    'coaching_framework', 'onboarding', 'conversation'
  )),
  source_id text,
  metadata jsonb default '{}',
  created_at timestamptz not null default now()
);

-- IVFFlat index for fast cosine similarity search
create index on public.knowledge_chunks using ivfflat (embedding vector_cosine_ops)
  with (lists = 100);

-- ──────────────────────────────────────────────────────────────
-- AI conversations
-- ──────────────────────────────────────────────────────────────
create table public.ai_conversations (
  id uuid primary key default gen_random_uuid(),
  profile_id uuid not null references public.profiles(id) on delete cascade,
  session_id text not null unique,
  messages jsonb not null default '[]',
  insights_extracted boolean not null default false,
  created_at timestamptz not null default now()
);

-- ──────────────────────────────────────────────────────────────
-- Row Level Security
-- ──────────────────────────────────────────────────────────────
alter table public.profiles enable row level security;
alter table public.onboarding enable row level security;
alter table public.client_reels enable row level security;
alter table public.competitor_reels enable row level security;
alter table public.weekly_scripts enable row level security;
alter table public.weekly_reports enable row level security;
alter table public.content_pillars enable row level security;
alter table public.knowledge_chunks enable row level security;
alter table public.ai_conversations enable row level security;

-- Profiles: users see their own; admin sees all
create policy "profiles_self" on public.profiles
  for all using (auth.uid() = id);

create policy "profiles_admin" on public.profiles
  for all using (
    exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin')
  );

-- Onboarding: own data only (admin via service key from workers)
create policy "onboarding_self" on public.onboarding
  for all using (profile_id = auth.uid());

create policy "onboarding_admin" on public.onboarding
  for all using (
    exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin')
  );

-- Client reels: own data only
create policy "client_reels_self" on public.client_reels
  for select using (profile_id = auth.uid());

create policy "client_reels_admin" on public.client_reels
  for all using (
    exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin')
  );

-- Competitor reels: readable by all authenticated users
create policy "competitor_reels_read" on public.competitor_reels
  for select using (auth.uid() is not null);

-- Weekly scripts: own scripts only
create policy "weekly_scripts_self" on public.weekly_scripts
  for select using (profile_id = auth.uid());

create policy "weekly_scripts_admin" on public.weekly_scripts
  for all using (
    exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin')
  );

-- Weekly reports: readable by all authenticated users
create policy "weekly_reports_read" on public.weekly_reports
  for select using (auth.uid() is not null);

-- Content pillars: own data only
create policy "content_pillars_self" on public.content_pillars
  for select using (profile_id = auth.uid());

create policy "content_pillars_admin" on public.content_pillars
  for all using (
    exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin')
  );

-- Knowledge chunks: readable by all authenticated (needed for AI queries)
create policy "knowledge_chunks_read" on public.knowledge_chunks
  for select using (auth.uid() is not null);

-- AI conversations: own data only
create policy "ai_conversations_self" on public.ai_conversations
  for all using (profile_id = auth.uid());

create policy "ai_conversations_admin" on public.ai_conversations
  for all using (
    exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin')
  );

-- ──────────────────────────────────────────────────────────────
-- Vector similarity search function (used in Phase 3 RAG)
-- ──────────────────────────────────────────────────────────────
create or replace function match_knowledge(
  query_embedding vector(1536),
  match_count int default 10,
  filter_source_type text default null
)
returns table (
  id uuid,
  content text,
  source_type text,
  source_id text,
  metadata jsonb,
  similarity float
)
language sql stable
as $$
  select
    id, content, source_type, source_id, metadata,
    1 - (embedding <=> query_embedding) as similarity
  from public.knowledge_chunks
  where (filter_source_type is null or source_type = filter_source_type)
    and embedding is not null
  order by embedding <=> query_embedding
  limit match_count;
$$;
